### ISSUE TITLE
Password generator stalls when invoked

### ISSUE THREAD

**Issue by benjamin-smith** [deanishe/alfred-pwgen#4]
![image](https://cloud.githubusercontent.com/assets/1483102/16311193/8e018190-393d-11e6-9930-0aec409d14e8.png)

Never moves beyond this point. Started seemingly randomly about 2 weeks ago, worked fine before that.

Not familiar with debugging Alfred Workflows, what other info can I provide?

![image](https://cloud.githubusercontent.com/assets/1483102/16313011/34dc9070-3945-11e6-8862-864b1073a937.png)

Using release v1.3.

**Comment by deanishe** [comment]
Could you provide:

- Alfred version number
- Any output in Alfred's debugger

**Comment by benjamin-smith** [comment]
Alfred `v2.8.5 (439)`

Nothing shows in the debugger for any command, see Gif: https://www.dropbox.com/s/c0m2d3eywwdjpig/alfred.gif?dl=0

The debugger is working for other workflows.

**Comment by rob-anderson** [comment]
I am also experiencing this problem.  Rebooting the entire machine fixes it.

Thanks for this workflow btw - I use it all the time.

**Comment by benjamin-smith** [comment]
I've rebooted a few times, with unfortunately no change in behavior.

**Comment by rob-anderson** [comment]
This keeps recurring for me.

**Comment by deanishe** [comment]
It might be one of the generators. Which ones do you have turned on?

**Comment by benjamin-smith** [comment]
Not sure! The `pwconf` command also hangs indefinitely...

![image](https://cloud.githubusercontent.com/assets/1483102/16955016/28692f90-4da1-11e6-9823-8f79244cd519.png)

**Comment by deanishe** [comment]
@benjamin-smith Update Alfred and reboot your machine.

There is a known bug in older versions of Alfred 2 that causes workflows to hang.

**Comment by peelman** [comment]
yeah...still having this issue, even using the version just released in february and the latest Alfred betas.

**Comment by peelman** [comment]
I end up with a number of stalled/orphaned processes treed under Alfred.

![screen shot 2017-03-14 at 2 00 57 pm](https://cloud.githubusercontent.com/assets/52936/23915292/039eea22-08bf-11e7-90a1-10201e19d9f7.png)

**Comment by peelman** [comment]
Couple of notes:

Removing `~/Library/Application Support/Alfred 3/Workflows/net.deanishe.alfred-pwgen` fixed my problem.  When using `pwgen` next everything worked as expected.

Looking at the two directories, two things jumped out at me: I had a settings.json.lock file that had apparently been stuck in place since December of 2015.

My settings.json only showed a couple of minor differences:

![screen shot 2017-03-14 at 2 11 40 pm](https://cloud.githubusercontent.com/assets/52936/23915691/2ff28ff6-08c0-11e7-863a-03c860b6eaec.png)

So my guess would be that a bug or crash caused the lock file to not be removed and the lock file being persistently present was causing some issues and the script was not properly timing out or displaying a warning while waiting for the lock to be released, and none of these were problems with the old versions of `pwgen` I was using / hacking on in order to continue functioning.

So I guess ignore my previous two messages, unless you find this thread while working through similar problems, in which case, go to the aforementioned path and try removing an errant lock file.

@deanishe thanks for your hard work thus far 🥇.  My only humble request would be some lock file timestamp checking and/or some timeouts implemented for safety!

**Comment by deanishe** [comment]
> some lock file timestamp checking and/or some timeouts implemented for safety!

Will do. Clearly I was planning to do something along these lines, as Alfred-Workflow writes the PID to the lockfile, but I never got round to adding the code to read and check it :pensive:

**Comment by deanishe** [comment]
Hopefully fixed the hanging in [v2.0.2](https://github.com/deanishe/alfred-pwgen/releases/tag/v2.0.2) by updating Alfred-Workflow.
